In [34]:
import pandas as pd
import numpy as np

In [35]:
import pandas as pd

df = pd.read_excel('E:/AIML-main/sem4 ml project/ml/datasets/Telco_customer_churn.xlsx')
print("Raw shape:", df.shape)

Raw shape: (7043, 33)

In [36]:
print(df.columns.tolist())

['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value', 'Churn Score', 'CLTV', 'Churn Reason']

In [39]:

df['Total Charges'].dtype

dtype('O')

In [40]:
df.isnull()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [41]:

df.isnull().sum()        # Count missing per column

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [42]:
# drop irrelevant and leaky columns
df = df.drop(columns=[
    'CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code', 
    'Lat Long', 'Latitude', 'Longitude', 
    'Churn Label', 'Churn Score', 'Churn Reason'
])
print("Shape after dropping columns:", df.shape)

Shape after dropping columns: (7043, 21)

In [43]:
# fix total charges the column causing trouble
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')
print("Nulls in Total Charges before fix:", df['Total Charges'].isnull().sum())

df['Total Charges'] = df['Total Charges'].fillna(0)
print("Nulls in Total Charges after fix:", df['Total Charges'].isnull().sum())

Nulls in Total Charges before fix: 11
Nulls in Total Charges after fix: 0

In [44]:
df.dropna()              # Drop rows with *any* missing values
df.dropna(axis=1)        # Drop columns with missing values

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value,CLTV
0,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,3239
1,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,2701
2,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,1,5372
3,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1,5003
4,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,...,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,1,5340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Female,No,No,No,72,Yes,No,No,No internet service,No internet service,...,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),21.15,1419.40,0,5306
7039,Male,No,Yes,Yes,24,Yes,Yes,DSL,Yes,No,...,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,0,2140
7040,Female,No,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,...,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,0,5560
7041,Female,No,Yes,Yes,11,No,No phone service,DSL,Yes,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0,2793
7042,Male,No,No,No,66,Yes,No,Fiber optic,Yes,No,...,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,0,5097

In [45]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Length: 7043, dtype: bool

In [46]:
df.drop_duplicates()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value,CLTV
0,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,3239
1,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,2701
2,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,1,5372
3,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1,5003
4,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,...,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,1,5340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Female,No,No,No,72,Yes,No,No,No internet service,No internet service,...,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),21.15,1419.40,0,5306
7039,Male,No,Yes,Yes,24,Yes,Yes,DSL,Yes,No,...,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,0,2140
7040,Female,No,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,...,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,0,5560
7041,Female,No,Yes,Yes,11,No,No phone service,DSL,Yes,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0,2793
7042,Male,No,No,No,66,Yes,No,Fiber optic,Yes,No,...,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,0,5097

In [47]:
df.describe()

       Tenure Months  Monthly Charges  Total Charges  Churn Value         CLTV
count    7043.000000      7043.000000    7043.000000  7043.000000  7043.000000
mean       32.371149        64.761692    2279.734304     0.265370  4400.295755
std        24.559481        30.090047    2266.794470     0.441561  1183.057152
min         0.000000        18.250000       0.000000     0.000000  2003.000000
25%         9.000000        35.500000     398.550000     0.000000  3469.000000
50%        29.000000        70.350000    1394.550000     0.000000  4527.000000
75%        55.000000        89.850000    3786.600000     1.000000  5380.500000
max        72.000000       118.750000    8684.800000     1.000000  6500.000000

In [48]:
df.dtypes

Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges        float64
Churn Value            int64
CLTV                   int64
dtype: object

In [49]:
df = df.rename(columns={'Churn Value': 'Churn'})
print(df['Churn'].value_counts())

Churn
0    5174
1    1869
Name: count, dtype: int64

In [50]:
# Check CLTV for nulls too (since we never explicitly checked it)
print("Nulls in CLTV:", df['CLTV'].isnull().sum())

Nulls in CLTV: 0

In [51]:
#  Full missing-value check across ALL columns (final safety net)
print(df.isnull().sum().sum())
print(df.isnull().sum()[df.isnull().sum() > 0])

0
Series([], dtype: int64)

In [52]:
# once agin check for dublicate values
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [53]:
df_encoded = pd.get_dummies(df, drop_first=True)
print(df_encoded.shape)

(7043, 32)

In [54]:
# Final verification before saving (this is the step that would have caught the earlier problem)
print("Total nulls in final dataset:", df_encoded.isnull().sum().sum())
assert df_encoded.isnull().sum().sum() == 0, "Still have nulls — do not save yet!"
print("Clean. Safe to save.")

Total nulls in final dataset: 0
Clean. Safe to save.

In [55]:
correlations = df_encoded.corr()['Churn'].sort_values(ascending=False)
print(correlations)

Churn                                     1.000000
Internet Service_Fiber optic              0.308020
Payment Method_Electronic check           0.301919
Monthly Charges                           0.193356
Paperless Billing_Yes                     0.191825
Senior Citizen_Yes                        0.150889
Streaming TV_Yes                          0.063228
Streaming Movies_Yes                      0.061382
Multiple Lines_Yes                        0.040102
Phone Service_Yes                         0.011942
Gender_Male                              -0.008612
Multiple Lines_No phone service          -0.011942
Device Protection_Yes                    -0.066160
Online Backup_Yes                        -0.082255
Payment Method_Mailed check              -0.091683
CLTV                                     -0.127463
Payment Method_Credit card (automatic)   -0.134302
Partner_Yes                              -0.150448
Tech Support_Yes                         -0.164674
Online Security_Yes                      -0.171226
Contract_One year                        -0.177820
Total Charges                            -0.198324
Internet Service_No                      -0.227890
Online Security_No internet service      -0.227890
Streaming TV_No internet service         -0.227890
Tech Support_No internet service         -0.227890
Online Backup_No internet service        -0.227890
Device Protection_No internet service    -0.227890
Streaming Movies_No internet service     -0.227890
Dependents_Yes                           -0.248542
Contract_Two year                        -0.302253
Tenure Months                            -0.352229
Name: Churn, dtype: float64

In [56]:
df_encoded.to_csv('E:/AIML-main/sem4 ml project/ml/datasets/telco_churn_cleaned.csv', index=False)